#include<stdio.h>
int main()
{
    int t,n,s[1001],val,i,j,swap,v;
    scanf("%d",&t);
    while(t--)
    {
        scanf("%d",&n);
        for(i=0;i<n;i++)
            scanf("%d",&s[i]);
        for(i=0;i<n-1;i++)
        {
            for(j=0;j<n-i-1;j++)
            {
                if(s[j]>s[j+1])
                {
                    swap=s[j];
                    s[j]=s[j+1];
                    s[j+1]=swap;
                }
            }
        }
        for(i=0;i<n-1;i++)
        {
            if(i==0)
                val=s[1]-s[0];
            else
            {
                v=s[i+1]-s[i];
                if(v<val)
                    val=v;
            }
        }
        printf("%d\n",val);
    }
}
