#include<bits/stdc++.h>
using namespace std;
int main()
{
    long long t,n,s,k,i,ara[10000],l,r,p,v,j;
    cin>>t;
    while(t--)
    {
        p=0;
        cin>>n>>s>>k;
        for(i=0;i<k;i++)
            cin>>ara[i];
        sort(ara,ara+k);
        for(i=0;i<k;i++)
        {
            if(ara[i]==s)
            {
                p=1;
                v=i;
                break;
            }
        }
        if(p==0)
            cout<<"0"<<endl;
        else
        {
            for(j=v-1;j>=0;j--)
            {
                if(ara[j]+1==ara[j+1])
                    continue;
                else
                {
                    l=ara[j+1]-1;
                    p=2;
                    break;
                }
            }
            if(p==1)
            {
                if(ara[0]==1)
                {
                    for(j=v+1; j<k; j++)
                    {
                        if(ara[j-1]+1==ara[j])
                            continue;
                        else
                        {
                            r=ara[j-1]+1;
                            p=2;
                            break;
                        }
                    }
                    if(p==2)
                        cout<<r-s<<endl;
                    else
                        cout<<ara[k-1]+1-s<<endl;
                }
                else
                {
                    l=ara[0]-1;
                    for(j=v+1; j<k; j++)
                    {
                        if(ara[j-1]+1==ara[j])
                            continue;
                        else
                        {
                            r=ara[j-1]+1;
                            p=2;
                            break;
                        }
                    }
                    if(p==2)
                    {
                        if(s-l<=r-s)
                            cout<<s-l<<endl;
                        else
                            cout<<r-s<<endl;
                    }
                    else
                    {
                        if(ara[k-1]+1<=n)
                        {
                            r=ara[k-1]+1;
                            if(s-l<=r-s)
                                cout<<s-l<<endl;
                            else
                                cout<<r-s<<endl;
                        }
                        else
                            cout<<s-l<<endl;
                    }
                }
            }
            else
            {
                for(j=v+1; j<k; j++)
                {
                    if(ara[j-1]+1==ara[j])
                        continue;
                    else
                    {
                        r=ara[j-1]+1;
                        p=3;
                        break;
                    }
                }
                if(p==2)
                {
                    if(ara[k-1]+1<=n)
                    {
                        r=ara[k-1]+1;
                        if(r-s<=s-l)
                            cout<<r-s<<endl;
                        else
                            cout<<s-l<<endl;
                    }
                    else
                        cout<<s-l<<endl;
                }
                else
                {
                    if(r-s<=s-l)
                        cout<<r-s<<endl;
                    else
                        cout<<s-l<<endl;
                }
            }
        }
    }
    return 0;
}
