#include<bits/stdc++.h>
#include<string>
using namespace std;
#define fastio ios_base::sync_with_stdio(false);cin.tie(NULL)

int main()
{
    fastio;
    int t,n,m,i,j,x,y,p;
    char ara[100][100];
    cin>>t;
    while(t--)
    {
        x=-1;
        y=-1;
        p=0;
        cin>>n>>m;
        for(i=0;i<n;i++)
        {
            for(j=0;j<m;j++)
            {
                cin>>ara[i][j];
            }
        }
        for(i=0;i<n;i++)
        {
            if(x!=-1 || y!=-1)
                break;
            for(j=0;j<m;j++)
            {
                if(ara[i][j]=='R')
                {
                    x=(i+j)%2;
                    break;
                }
                if(ara[i][j]=='W')
                {
                    y=(i+j)%2;
                    break;
                }
            }
        }
        if(x==-1 && y==-1)
        {
            cout<<"YES"<<"\n";
            for(i=0;i<n;i++)
            {
                for(j=0;j<m;j++)
                {
                    if((i+j)%2==0)
                        cout<<"R";
                    else
                        cout<<"W";
                }
                cout<<"\n";
            }
            continue;
        }
        if(x!=-1)
        {
            for(i=0;i<n;i++)
            {
                if(p==1)
                    break;
                for(j=0;j<m;j++)
                {
                    if((i+j)%2==x)
                    {
                        if(ara[i][j]=='W')
                        {
                            p=1;
                            break;
                        }
                        ara[i][j]='R';
                    }
                    else
                    {
                        if(ara[i][j]=='R')
                        {
                            p=1;
                            break;
                        }
                        ara[i][j]='W';
                    }
                }
            }
            if(p==1)
            {
                cout<<"NO"<<"\n";
                continue;
            }
            cout<<"YES"<<"\n";
            for(i=0;i<n;i++)
            {
                for(j=0;j<m;j++)
                    cout<<ara[i][j];
                cout<<"\n";
            }
        }
        else
        {
            for(i=0;i<n;i++)
            {
                if(p==1)
                    break;
                for(j=0;j<m;j++)
                {
                    if((i+j)%2==y)
                    {
                        if(ara[i][j]=='R')
                        {
                            p=1;
                            break;
                        }
                        ara[i][j]='W';
                    }
                    else
                    {
                        if(ara[i][j]=='W')
                        {
                            p=1;
                            break;
                        }
                        ara[i][j]='R';
                    }
                }
            }
            if(p==1)
            {
                cout<<"NO"<<"\n";
                continue;
            }
            cout<<"YES"<<"\n";
            for(i=0;i<n;i++)
            {
                for(j=0;j<m;j++)
                    cout<<ara[i][j];
                cout<<"\n";
            }
        }
    }
    return 0;
}
